version: '3'

services:
  fastapi:
    image: ${IMAGE_NAME}
    container_name: ${IMAGE_NAME}
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - ${ACCESS_PORT}:8000
    restart: always
    tty: true